### PR TITLE
Fix KeyError on processing batches

### PR DESCRIPTION
**Pull request by appleparan**
## Issue
* I got `KeyError` when processing batches.

```
Traceback (most recent call last):
  File "/home/appleparan/src/LogicKor/generator.py", line 134, in <module>
    process_data(df_questions, args.batch_size, args.num_workers)
  File "/home/appleparan/src/LogicKor/generator.py", line 123, in process_data
    results = list(executor.map(process_batch, dataloader))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/3.11.8/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
...
  File "/home/appleparan/src/LogicKor/generator.py", line 67, in process_batch
    for output in llm.generate(single_turn_questions, sampling_params):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 199, in generate
    prompt = prompts[i] if prompts is not None else None
             ~~~~~~~^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/pandas/core/series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/pandas/core/series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 0
```

## Reason
* Identied a `KeyError` because `vllm` expects argument of `generate` as `str` or `list[str]`, whereas `LogicKor` uses a pandas `Series`.
* This commit resolve this issue by converting `Series` to `list[str]` temporarily

## Remaining issues 
* Disable `ThreadPoolExecutor` due to conflict with `vllm` scheduler.
```
Traceback (most recent call last):                                                                                                                                     | 0/9 [00:00<?, ?it/s]
  File "/home/appleparan/src/LogicKor/generator.py", line 124, in <module>                                                                                           | 0/19 [00:00<?, ?it/s]
    process_data(df_questions, args.batch_size, args.num_workers)                                                                                                    | 0/15 [00:00<?, ?it/s]
  File "/home/appleparan/src/LogicKor/generator.py", line 113, in process_data                                                                                       | 0/23 [00:00<?, ?it/s]
    results = list(executor.map(process_batch, dataloader))                                                                                                          | 0/25 [00:00<?, ?it/s]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                          | 0/30 [00:00<?, ?it/s]
  File "/home/appleparan/.pyenv/versions/3.11.8/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator                                            | 0/37 [00:00<?, ?it/s]
    yield _result_or_cancel(fs.pop())                                                                                                                                | 0/38 [00:00<?, ?it/s]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                | 0/41 [00:00<?, ?it/s]
  File "/home/appleparan/.pyenv/versions/3.11.8/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel                                          | 0/42 [00:00<?, ?it/s]
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/3.11.8/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/3.11.8/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/appleparan/.pyenv/versions/3.11.8/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/src/LogicKor/generator.py", line 72, in process_batch
    for output in llm.generate(single_turn_questions, sampling_params)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 214, in generate
    return self._run_engine(use_tqdm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 242, in _run_engine
    step_outputs = self.llm_engine.step()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 557, in step
    seq_group_metadata_list, scheduler_outputs = self.scheduler.schedule()
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/vllm/core/scheduler.py", line 890, in schedule
    scheduler_outputs = self._schedule()
                        ^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/vllm/core/scheduler.py", line 863, in _schedule
    return self._schedule_default()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/vllm/core/scheduler.py", line 756, in _schedule_default
    assert len(running_scheduled.prefill_seq_groups) == 0
           ^^^
```
* Tokens are not generated sometimes on generation of multi-turn outputs.
```
Traceback (most recent call last):
  File "/home/appleparan/src/LogicKor/generator.py", line 131, in <module>
    process_data(df_questions, args.batch_size, args.num_workers)
  File "/home/appleparan/src/LogicKor/generator.py", line 120, in process_data
    results = list(map(process_batch, dataloader))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/src/LogicKor/generator.py", line 95, in process_batch
    for output in llm.generate(multi_turn_questions, sampling_params)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 214, in generate
    return self._run_engine(use_tqdm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 242, in _run_engine
    step_outputs = self.llm_engine.step()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 557, in step
    seq_group_metadata_list, scheduler_outputs = self.scheduler.schedule()
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/vllm/core/scheduler.py", line 890, in schedule
    scheduler_outputs = self._schedule()
                        ^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/vllm/core/scheduler.py", line 863, in _schedule
    return self._schedule_default()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/vllm/core/scheduler.py", line 733, in _schedule_default
    remaining_swapped, swapped_in = self._schedule_swapped(
                                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appleparan/.pyenv/versions/logickor/lib/python3.11/site-packages/vllm/core/scheduler.py", line 548, in _schedule_swapped
    assert num_new_tokens == 1
           ^^^^^^^^^^^^^^^^^^^
AssertionError
```

### CODE REVIEW

**Comment by appleparan** [comment]
## Remaining Issues 
* ~Tokens are not generated sometimes on generation of multi-turn outputs.~
    *  It seems to appear if GPU doesn't have sufficient memory, decreasing `batch_size` removes this error
* Disable `ThreadPoolExecutor` due to conflict with `vllm` scheduler.
    * Still investigating the issue. 
    * However, I don't know why we need to use `ThreadPoolExecutor`. It has only 42 questions and not IO bounded jobs.

**Comment by realsigridjin** [comment]
@appleparan hello, thanks for your contributions. I agree your point that we don't need to use ThreadPoolExecutor at this moment due to the small amount of questions.

**Comment by StableFluffy** [comment]
https://github.com/instructkr/LogicKor/blob/main/generator.py

At latest generator.py we reverted the change @sigridjineth made; such as ThreadPoolExecutor things.
Is there any need to merge this pr?

**Comment by appleparan** [comment]
It seems we don't need to merge it. I'll close the PR.

**Pull request closed without merging**
